action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 100000


runner: "parallel"
train_buffer_size: 5000
train_batch_size: 128
update_rate: 4
target_update_interval: 200

agent_output_type: q

learner: "q_learner"
mixer: "qmix"
mixing_embed_dim: 32
hypernet_embed: 64
lr: 0.001
td_lambda: 0.6
q_lambda: False

# rnn layer normalization
use_layer_norm: False

name: "qmix"