env: "replenishment"

env_args:
  key: "replenishment_efficient_env-v0"
  map_name: "sku1000.standard"
  n_agents: 1000
  task_type: "sku1000.single_store.standard"
  mode: train
  time_limit: 100
  reward: "reward2"

t_max: 2000000