mac: "basic_mac"
# --- Log ---
log_episodes: 200
log_root_path: results
save_log: True
use_tensorboard: False
log_interval: 5000

# --- RL hyperparameters ---
gamma: 0.99
lr: 0.0005
optim_alpha: 0.99
optim_eps: 0.00001
grad_norm_clip: 10

# --- Agent parameters ---
agent: "rnn"
hidden_dim: 64
obs_agent_id: True
obs_last_action: True
save_probs: False
use_individual_rewards: True
# --- evaluate ---
evaluate: True
evaluate_episodes: 32
evaluate_interval: 10000
evaluate_batch_size: 2

# --- sample ---
num_env_runner: 1
asynchronous_env: False
shared_buffer_size: 8

# --- infer ---
base_port: 16400
num_inference_worker: 1
infer_batch_size: 1
infer_device: cuda

